trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install -g newman
  displayName: 'Install Newman'

- script: npm install -g newman-reporter-htmlextra
  displayName: 'Install reporter'

- script: newman run storecollection.json -g postman_globals.json --reporters cli,htmlextra
  displayName: 'Store Collection'

- script: newman run petCollection.json -g postman_globals.json --reporters cli,htmlextra
  displayName: 'petCollection'